@host = localhost:7071
@instanceId = <Retrieve from kickoff request>
@storagekey = <Retrieve from kickoff request - NEVER check-in to SCM>


###

###Kickoff New Orchestrator
POST http://{{host}}/api/DurableFunction_HttpStart

###Get Orchestrator Status
GET http://{{host}}/runtime/webhooks/durabletask/instances/{{instanceId}}?taskHub=DurableFunctionsHub&connection=Storage&code={{storagekey}}

###Terminate Orchestrator
POST http://{{host}}/runtime/webhooks/durabletask/instances/{{instanceId}}/terminate?reason=WrongInstanceId&taskHub=DurableFunctionsHub&connection=Storage&code={{storagekey}}

###Purge Orchestrator
DELETE http://{{host}}/runtime/webhooks/durabletask/instances/{{instanceId}}?taskHub=DurableFunctionsHub&connection=Storage&code={{storagekey}}
